Add fn init_emit()
sharksforarms/deku pull request #179
Opened 2021-02-18 04:26 UTC by wcampbell0x2a

Grouped like initialize variables into one function that were copied between the emit functions for write/read

2021-02-18 13:50 UTC, sharksforarms requested changes
Couple small changes, looks good! :+1:

2021-02-18 13:50 UTC, sharksforarms commented on deku-derive/src/lib.rs
> +    fn init_emit(
`emit_enum_common` might be a better name

2021-02-18 13:50 UTC, sharksforarms commented on deku-derive/src/lib.rs
> +    /// Create like initialize variables for emit write/read functions
```suggestion
    /// Create common initializer variables for enum_emit read/write functions
```

2021-02-18 13:50 UTC, sharksforarms commented on deku-derive/src/lib.rs
> +        (
Clippy error here, may be worth refactoring into a struct?

2021-02-23 18:11 UTC, sharksforarms commented
Will need a rebase :)

2021-03-02 21:18 UTC, wcampbell0x2a commented
- Refactored into struct, with a `try_from` from `DekuData` and then deconstruct into the variables.

2021-03-02 22:56 UTC, sharksforarms reviewed
Thanks! The same could probably be done for emit_struct in read/write. Would you be interested in doing that too?

2021-03-02 22:56 UTC, sharksforarms commented on deku-derive/src/lib.rs
> +/// Common variables from `DekuData` for enum_emit read/write functions
```suggestion
/// Common variables from `DekuData` for `emit_enum` read/write functions
```

2021-03-02 22:56 UTC, sharksforarms commented on deku-derive/src/lib.rs
> +    /// Create common initializer variables for enum_emit read/write functions
```suggestion
    /// Create common initializer variables for `emit_enum` read/write functions
```

2021-03-02 22:56 UTC, sharksforarms commented on deku-derive/src/macros/deku_read.rs
> +    //let (imp, wher, variants, ident, id, id_type, id_args) = input.init_emit()?;
leftover comment

2021-03-02 22:56 UTC, sharksforarms commented on deku-derive/src/macros/deku_read.rs
> +    let DekuDataEnum {
This look good :+1:

2021-03-02 23:58 UTC, wcampbell0x2a commented
> Thanks! The same could probably be done for emit_struct in read/write. Would you be interested in doing that too?

sure!

2021-03-03 00:42 UTC, wcampbell0x2a commented
Alright that should be good

2021-03-11 20:29 UTC, sharksforarms approved these changes
Thanks!

2021-03-11 20:29 UTC, merged