Release 0.18
sharksforarms/deku pull request #477
Opened 2024-09-05 15:53 UTC by sharksforarms

- **update deps**
- **0.18 changelog**
- **fix: fxhashmap update**

2024-09-05 23:23 UTC, wcampbell0x2a requested changes

2024-09-05 23:23 UTC, wcampbell0x2a commented on CHANGELOG.md
>  - Add attributes `seek_from_start`, `seek_from_current`, `seek_from_end`, and `seek_rewind` to control the position of the reader before reading a field ([#360](https://github.com/sharksforarms/deku/
This wasn't you, this was me. However, we should mention that `Seek` is now required.

2024-09-05 23:23 UTC, wcampbell0x2a commented on CHANGELOG.md
> +- The use of bits parsing is now an optional feature. If bit-level parsing is not usefull for your application, you can disable it to get some performance benefits. ([#446](https://github.com/sharksf
```suggestion
- The use of bits parsing is now an optional feature. If bit-level parsing is not useful for your application, you can disable it to get some performance benefits. ([#446](https://github.com/sharksforarms/deku/pull/446))
```

2024-09-06 15:29 UTC, sharksforarms commented
@wcampbell0x2a done

2024-09-06 17:12 UTC, wcampbell0x2a submitted a review, later dismissed

2024-09-06 22:21 UTC, wcampbell0x2a commented
I think https://github.com/sharksforarms/deku/pull/461 wasn't released last time either? Could deserve a mention.

2024-09-07 15:16 UTC, merged